### ISSUE TITLE
Errors while running topic_mining

### ISSUE THREAD

**Issue by talwarabhimanyu** [JiachengLi1995/UCTopic#2]
Hello, thanks for making this repo available. I'm trying the `topic_mining` example provided in the repo's Overview section. I have not made any code changes at my end and the code runs into errors. Here is a [Colab notebook](https://colab.research.google.com/drive/181EOG_roXqB0Ktry6vk9KJenlJeihVUO?usp=sharing) reproducing it. I do understand the variable `n_clusters` is set to `[15,25]` in the example which is more than the number of `sentences` which is 5, however even after taking a lower `n_clusters=[2,3]` the code throws an error. Request you to take a look, thanks!

Here is the error log without changing anything in the example:

```
Normalize phrases: 100%|██████████| 5/5 [00:00<00:00, 97.04it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-41ec3e394e7f>](https://localhost:8080/#) in <module>
     13 # len(sentences) is equal to len(spans)
     14 output_data, topic_phrase_dict = topic_tool.topic_mining(sentences, spans, \
---> 15                                                    n_clusters=[15, 25])

2 frames
[/usr/local/lib/python3.7/dist-packages/uctopic/kmeans.py](https://localhost:8080/#) in fit_predict(self, X, centroids, verbose)
    151         start_time = time()
    152         if centroids is None:
--> 153             self.centroids = X[np.random.choice(batch_size, size=[self.n_clusters], replace=False)]
    154         else:
    155             self.centroids = centroids

mtrand.pyx in numpy.random.mtrand.RandomState.choice()

ValueError: Cannot take a larger sample than population when 'replace=False'
```

**Comment by JiachengLi1995** [comment]
I checked it in your Colab notebook.

For the error you posted here, it's because the n_clusters is larger than the number of samples.
After I changed it, I got another error. This new error is because the sentences are too few to have ccl_finetune.
Please set `ccl_finetune=False` if you have a few instances:
`output_data, topic_phrase_dict = topic_tool.topic_mining(sentences, spans, n_clusters=[2, 2], ccl_finetune=False)`
Then, you should be fine.

Thanks for your interest in our project. Any other questions, please let me know.

**Comment by talwarabhimanyu** [comment]
Thanks so much for your prompt follow up!
